[cosmic-ray]
module-path = "src/linear_search.py"
python-version = ""
timeout = 10.0
excluded-modules = []

[cosmic-ray.test-command]
command = "pytest tests/test_random.py -x -q"

[cosmic-ray.distributor]
name = "local"
